// <auto-generated />
using System;
using JotterService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JotterService.PostgresMigrations.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220227131834_SecretCypher")]
    partial class SecretCypher
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JotterService.Domain.Password", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerNumber")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.HasKey("Id");

                    b.HasIndex("Title");

                    b.HasIndex("Url");

                    b.ToTable("Password", (string)null);
                });

            modelBuilder.Entity("JotterService.Domain.Password", b =>
                {
                    b.OwnsOne("JotterService.Domain.CypherText", "Secret", b1 =>
                        {
                            b1.Property<Guid>("PasswordId")
                                .HasColumnType("uuid");

                            b1.Property<byte[]>("Iv")
                                .IsRequired()
                                .HasColumnType("bytea");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("PasswordId");

                            b1.ToTable("Password");

                            b1.WithOwner()
                                .HasForeignKey("PasswordId");
                        });

                    b.Navigation("Secret")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
